name: AmongUs
description: "A PocketMine Mini-Game plugin."
author: alvin0319
main: alvin0319\AmongUs\AmongUs
version: 0.0.11
api: 3.0.0
website: https://github.com/alvin0319/AmongUs

commands:
  amongus:
    permission: amongus.command
    children:
      amongusmanage:
         permission: amongus.command.manage
         
permissions:
  amongus.command:
    default: true
    description: permission for amongus command
    children:
      amongus.command.manage:
        default: op
        description: permission for amongus manage command
        