name: AmongUs
description: "AmongUs plugin for MCBE"
author: alvin0319
main: alvin0319\AmongUs\AmongUs
version: 0.0.12
api: 3.0.0
website: https://github.com/alvin0319/AmongUs

permissions:
    amongus.command:
        default: true
        description: permission for amongus command.
        children:
            amongus.command.manage:
                default: op
                description: permission for amongus manage command.